project:
  type: website
  output-dir: docs

website:
  title: "Andrew M. Demetriou"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Licensing"
        href: licenses.qmd
    right:
      - icon: github
        href: https://github.com/andrew0302/portfolio

  page-footer:
    left: |
     © 2025 Andrew Lastname  •  Code licensed under [MIT](https://opensource.org/licenses/MIT)  •  Content under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
