project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: "HOME"
        href: index.qmd 
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Licensing"
        href: licenses.qmd
    right:
      - text: "email me:"
      - icon: envelope
        href: "mailto:andrew.m.demetriou@gmail.com"

  page-footer: |
     © 2025 Andrew M. Demetriou  •  Code licensed under [MIT](https://opensource.org/licenses/MIT)  •  Content under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
